name: Practical Events 1
on:
    pull_request: # Trigger when a pull request is opened
        types: ["opened"] # Trigger only when a pull request is opened
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output event data
              run: echo "${{toJson(github.event)}}"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm test
            - name: Build Project
              run: npm run build
            - name: Deploy Project
              run: echo "Deploying to production..."
